### ISSUE TITLE
Bug - Litewallet iOS: Syncing is inaccurate

### ISSUE THREAD

**Issue by jeff169** [litecoin-foundation/litewallet-ios#13]
**Describe the bug**
Note: This is a different variation of an issue I previously logged.  Yesterday I received some LTC and it showed up in my history just fine.  It went through all the steps of processing (the percentage completion etc) and then showed as complete.  Balance was correctly updated and everything was good.  This morning, I sign in and see everything is good, but then all of a sudden, yesterday's transaction said something like "processing" and then magically disappeared from the history, and the balance was reduced.  So there is some sort of persistent sync issue, that seems like when you sign in, sometimes it may not sync correctly, and just lose the transaction.  It's like it connected to my history from before when I received the transaction.  Syncing the blockchain fixes it, but the transaction should not disappear right before my eyes.   I did notice something though.  When I synced with the blockchain, all my transactions showed as "complete" but when I signed in for the first time, I don't believe any of them showed any status except the one that disappeared, as mentioned above. So, it's like Litewallet had no memory of any of the transactions ever being completed, although only the most recent one disappeared. 

**To Reproduce**
Receive LTC and verify it shows as complete in the history.  Close out of Litewallet.  Sign in to Litewallet the following day.  Look at the history.  If the most recent receipt shows as "processing", it will disappear shortly.  

**Expected behavior**
Once a transaction is completed, it should remain in history. 

**Screenshots**
Did not have time to capture.  The transaction was gone before I realized what was about to happen. 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
iOS 14.4 iphone 11
 
**Additional context**

**Comment by kcw-grunt** [comment]
@jeff169 this was looked at at addressed in v3.4.0.  Should I close this ticket?

**Comment by jeff169** [comment]
I was just going to report this again.  I am still seeing transactions appear "in progress" or as "just now" even if they are a month old.  There are still syncing issues.  I took a couple screenshots - let me know if you need to see them.  This was just a couple days ago.

**Comment by kcw-grunt** [comment]
I was thinking maybe our node list is too stale.
